# Config file for automatic testing at travis-ci.org

language: python

python:
  - "3.5"
  - "3.4"
  - "3.3"
  - "2.7"

env:
  - DJANGO_VERSION=1.10.3
  - DJANGO_VERSION=1.9.11
  - DJANGO_VERSION=1.8.16

matrix:
  exclude:
    - python: "3.3"
      env: DJANGO_VERSION=1.9.11
    - python: "3.3"
      env: DJANGO_VERSION=1.10.3

before_install:
  - pip install codecov

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install -r requirements_test.txt
  - pip install -q Django==$DJANGO_VERSION

# command to run tests using coverage, e.g. python setup.py test
script: coverage run --source autosequence runtests.py

after_success:
  - codecov
