# Config file for automatic testing at travis-ci.org

language: python

python:
  - "3.7"
  - "3.6"

env:
  - DJANGO_VERSION=2

before_install:
  - pip install codecov pipenv

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - make install

# command to run tests using coverage, e.g. python setup.py test
script: make test

after_success:
  - codecov
