# Config file for automatic testing at travis-ci.org

language: python

python:
  - "3.6"

env:
  - DJANGO_VERSION=2

before_install:
  - pip install codecov poetry

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - poetry install

# command to run tests using coverage, e.g. python setup.py test
script: poetry run pytest

after_success:
  - codecov
